app/config/routes.rb
Rails.application.routes.draw do
  #get 'setting/index'

  mount Ckeditor::Engine => '/ckeditor'
  # devise_for :users

  resources :visitor do
    get 'historic', on: :member
  end

  get 'authorize' => 'auth#gettoken'

  match "/projects/finished", to: "projects#finished", via: :get
  resources :projects do
      post 'send_spices', on: :member
      post 'set_status', on: :member
      post 'set_objective_status', on: :member
      post 'assign_spices_to_user', on: :member

      get  'objective_validation', on: :member
      get 'assign_spices', on: :member
      get 'clone', on: :member
      get 'historic', on: :member
  end

  match "/projects/remove_user", to: "projects#remove_user_funding", via: :post
  match "/stats/spices", to: "stats#spices", via: :get
  match "/stats/users", to: "stats#user_data", via: :get
  match "/stats/project", to: "stats#project", via: :get
  match "/stats/admin", to: "stats#admin", via: :get
  match "/stats/change_status", to: "stats#change_status", via: :post
  match "/auth/login", to: "auth#login", via: :get
  match "/auth/logout", to: "auth#logout", via: :delete

  match "/setting", to: "setting#index", via: :get
  match "/setting", to: "setting#create", via: :post

  root "projects#index"
end

app/app/controllers/visitor_controller.rb
class VisitorController < ActionController::Base
  # GET /visitor
  # GET /visitor.json
  def index
    @projects = Project.where.not({status: 0}).order(:name)
  end

  # GET /visitor/1
  # GET /visitor/1.json
  def show
    @project = Project.find(params[:id])

    @number_of_project = Project.where({name: @project.name}).size
    respond_to do |format|
      format.html { render :show }
      format.pdf {
        render :pdf => 'show', :layout => 'application.pdf'
      }
    end
  end

  # GET /projects/:id/historic
  def historic
    @project = Project.find(params[:id])
    @projects = Project.where({name: @project.name}).order('created_at desc')
    render :historic
  end


end

app/app/helpers/visitor_helper.rb
module VisitorHelper
end

app/app/views/visitor/historic.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <nav class="navbar navbar-default" style="padding-bottom: 20px">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header" style="width: 20%">
            <a class="navbar-brand" rel="home" href="/" title="Buy Sell Rent Everyting">
              <%= image_tag "logo.jpg", :style => "max-height:35px; margin-top: -8px; margin-left:10px;" %>
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="h1 nav nav-center" style="text-align: center; width: 60%; display: inline-block">
                Hub Epitech Montpellier
            </div> 
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      <div class="container">
        <h1 class="text-center"><%= @projects.first.name %></h1>

        <% @projects.each_with_index do |p, index| %>
            <div class="text-center" style="font-size:large;margin-top:5%;">
                <%= link_to visitor_path(p) do %>
                    <span style='text-decoration: underline;'>Version <%= @projects.size - index %>:</span> Du <%= p.created_at.to_formatted_s(:db) %> au <%= p.objectives.last.date.to_formatted_s(:db) %>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: <%= Project.statuses[p.status].to_f * 100 / 9 %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                            <span style="color: <%= (Project.statuses[p.status] < 5 ? "black" : "#F1F1F1") %>;"><%= p.get_status %></span>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>

      </div>
      <div class="text-center">
        <%= link_to "/visitor" do %>Retour à l'ensemble des projets<% end %>
      </div>
    </div>
  </body>
</html>

app/app/views/visitor/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <nav class="navbar navbar-default" style="padding-bottom: 20px">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header" style="width: 20%">
            <a class="navbar-brand" rel="home" href="/" title="Buy Sell Rent Everyting">
              <%= image_tag "logo.jpg", :style => "max-height:35px; margin-top: -8px; margin-left:10px;" %>
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="h1 nav nav-center" style="text-align: center; width: 60%; display: inline-block">
                Hub Epitech Montpellier
            </div> 
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

        <div class="container">
        <% if @projects.empty? %>
            <div class="text-center" style="font-size: 20px">
            Aucun projet
            </div>
        <% else %>
            <% @projects.each do |p| %>
            <div class="list-group">
                <div class="list-group-item clearfix">
                <%= link_to visitor_path(p) do %>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: <%= Project.statuses[p.status].to_f * 100 / 9 %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                        <span style="color: <%= (Project.statuses[p.status] < 5 ? "black" : "#F1F1F1") %>;"><%= p.get_status %></span>
                        </div>
                    </div>
                    <%= p.name %>
                <% end %>
                <span class="pull-right">
                    <div class="btn-group" role="group" aria-label="...">
                        <%= link_to visitor_path(p, format: :pdf), :class => "btn btn-default", target: '_blank', data: {toggle: "tooltip", placement: "top"}, :title => "Voir le PDF" do %>
                            <span class="glyphicon glyphicon-download"></span>
                        <% end %>
                    </div>
                </span>
                </div>
            </div>
            <% end %>
        <% end %>
        </div>

     <div class="container footer">
      <div class="row">
        <hr>
        <div class="col-lg-12">
          <div class="col-md-8">
            <p class="muted pull-left">2017 Epitech Montpellier</p>
          </div>
          <div class="col-md-4">
            <a class="pull-right" target="_blank" href="https://www.evolt.io/">
              <%= image_tag "evolt.svg" %>
            </a>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/app/views/visitor/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <nav class="navbar navbar-default" style="padding-bottom: 20px">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header" style="width: 20%">
            <a class="navbar-brand" rel="home" href="/" title="Buy Sell Rent Everyting">
              <%= image_tag "logo.jpg", :style => "max-height:35px; margin-top: -8px; margin-left:10px;" %>
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="h1 nav nav-center" style="text-align: center; width: 60%; display: inline-block">
                Hub Epitech Montpellier
            </div> 
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

        <div class="container">
        
        <h1 class="text-center"><%= @project.name %></h1>
        <% if false == @project.git_hub.to_s.empty? %>
            <p><strong>GitHub:</strong> <%= @project.git_hub %></p>
        <% end %>

        <h2>Présentation</h2>
        <%= @project.description.html_safe %>

        <% @project.objectives.each_with_index do |objective, index| %>
            <h2 style='margin-top: 50px; text-align: center'><%= objective.objective_type %> <%= objective.date %></h2>
            <%= objective.description.html_safe %>
        <% end %>

        </div>
    </div>
  </body>
</html>

app/app/views/visitor/show.pdf.erb
<div class="container">
  <h1 class="text-center" style="text-align: center"><%= @project.name %></h1>
  
  <% if false == @project.git_hub.to_s.empty? %>  
    <h3>GitHub : <%= @project.git_hub %></h3>
  <% end %>
  
  <%= @project.description.html_safe %>

  <% @project.objectives.each do |obj| %>
    <h2><%= obj.objective_type %> <%= obj.date %></h2>
    <%= obj.description.html_safe %>
  <% end %>
</div>