app/config/routes.rb
Rails.application.routes.draw do
  #get 'setting/index'

  mount Ckeditor::Engine => '/ckeditor'
  # devise_for :users

  resources :visitor do
    get 'historic', on: :member
  end

  get 'authorize' => 'auth#gettoken'

  match "/projects/finished", to: "projects#finished", via: :get
  resources :projects do
      post 'send_spices', on: :member
      post 'set_status', on: :member
      post 'set_objective_status', on: :member
      post 'assign_spices_to_user', on: :member

      get  'objective_validation', on: :member
      get 'assign_spices', on: :member
      get 'clone', on: :member
      get 'historic', on: :member
  end

  match "/projects/remove_user", to: "projects#remove_user_funding", via: :post
  match "/stats/spices", to: "stats#spices", via: :get
  match "/stats/users", to: "stats#user_data", via: :get
  match "/stats/project", to: "stats#project", via: :get
  match "/stats/admin", to: "stats#admin", via: :get
  match "/stats/change_status", to: "stats#change_status", via: :post
  match "/auth/login", to: "auth#login", via: :get
  match "/auth/logout", to: "auth#logout", via: :delete

  match "/setting", to: "setting#index", via: :get
  match "/setting", to: "setting#create", via: :post

  root "projects#index"
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" rel="home" href="/" title="Buy Sell Rent Everyting">
              <%= image_tag "logo.jpg", :style => "max-height:35px; margin-top: -8px; margin-left:10px;" %>
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to "Soumettre un projet", new_project_path %></li>
              <li><%= link_to "Projets terminés",  projects_finished_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if user_logged_in %>
                    <% if current_user.role == 1 %>
                      <li>
                        <%= link_to "Paramètres",  setting_path %>
                      </li>
                      <li>
                        <%= link_to "Admin", stats_admin_path %>
                      </li>
                  <% end %>
                  <li>
                    <%= link_to "Mes " + money_name + " : " + current_user.spices.to_s, stats_spices_path %>
                    </li>
                    <li>
                      <%= link_to "Se déconnecter",  auth_logout_path, method: :delete %>
                    </li>
                <% else %>
                  <li>
                    <%= link_to "Se connecter", auth_login_path %>
                  </li>
                <% end %>
                </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      <div class="container">
        <% flash.each do |key, value| %>
            <%= content_tag :div, value, class: "flash #{key} text-center" %>
        <% end %>
      </div>

      <%= yield %>
    </div>

    <div class="container footer">
      <div class="row">
        <hr>
        <div class="col-lg-12">
          <div class="col-md-8">
            <p class="muted pull-left">2017 Epitech Montpellier</p>
          </div>
          <div class="col-md-4">
            <a class="pull-right" target="_blank" href="https://www.evolt.io/">
              <%= image_tag "evolt.svg" %>
            </a>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/app/views/layouts/application.pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>