app/config/routes.rb
Rails.application.routes.draw do
  #get 'setting/index'

  mount Ckeditor::Engine => '/ckeditor'
  # devise_for :users

  resources :visitor do
    get 'historic', on: :member
  end

  get 'authorize' => 'auth#gettoken'

  match "/projects/finished", to: "projects#finished", via: :get
  resources :projects do
      post 'send_spices', on: :member
      post 'set_status', on: :member
      post 'set_objective_status', on: :member
      post 'assign_spices_to_user', on: :member

      get  'objective_validation', on: :member
      get 'assign_spices', on: :member
      get 'clone', on: :member
      get 'historic', on: :member
  end

  match "/projects/remove_user", to: "projects#remove_user_funding", via: :post
  match "/stats/spices", to: "stats#spices", via: :get
  match "/stats/users", to: "stats#user_data", via: :get
  match "/stats/project", to: "stats#project", via: :get
  match "/stats/admin", to: "stats#admin", via: :get
  match "/stats/change_status", to: "stats#change_status", via: :post
  match "/auth/login", to: "auth#login", via: :get
  match "/auth/logout", to: "auth#logout", via: :delete

  match "/setting", to: "setting#index", via: :get
  match "/setting", to: "setting#create", via: :post

  root "projects#index"
end

app/app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def user_data
    @users = User.all
    @spices = 0

    @users.each do |u|
      if u.spices > 0
        @spices += u.spices
      end
    end

    render "data"
  end

  def spices
  end

  def project
    @project = Project.find(params[:id])
  end
  
  def admin
    if current_user.role == 1
      @admins = User.where({role: 1})
      @users = User.where({role: 0})
    end
  end

  def change_status
    if current_user.role == 1
      @user = User.find(params[:user_id])
      @user.role = params[:role].to_i
      if @user.save
        redirect_to stats_admin_path
      end
    else
      render :nothing => true, :status => :not_found
    end
  end
end

app/app/views/stats/admin.html.erb
<div class="container">
  <h2 class="text-center">Admininistrateurs</h2>

  <ul class="list-group">
    <% @admins.each do |a| %>
        <li class="list-group-item">
          <%= a.email %>
          <span class="pull-right">
            <%= link_to "Supprimer le status", stats_change_status_path({user_id: a.id, role: 0}), :class => "btn btn-xs btn-danger", :method => :post, data: { confirm: 'Etes vous sur de supprimer cet utilisateur comme administrateur ?' } %>
          </span>
        </li>
    <% end %>
  </ul>

  <h2 class="text-center">Utilisateurs</h2>
  <ul class="list-group">
    <% @users.each do |a| %>
        <li class="list-group-item">
          <%= a.email %>
          <span class="pull-right">
            <%= link_to "Passer en administrateur", stats_change_status_path({user_id: a.id, role: 1}), :class => "btn btn-xs btn-danger", :method => :post, data: { confirm: 'Etes vous sur de rajouter les droits à cette utilisateur ?' } %>
          </span>
        </li>
    <% end %>
  </ul>

</div>

app/app/views/stats/data.html.erb
<div class="container">
  <h2 class="text-center">Total des <%= money_name %> disponibles : <%= @spices %></h2>
  <table class="table">
    <thead>
    <tr>
      <th>email</th>
      <th><%= money_name %></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |u| %>
        <tr>
          <td><%= u.email %></td>
          <td><%= u.spices %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/app/views/stats/project.html.erb
<div class="container">
  <div class="row">
    <% @project.objectives.each do |o| %>
        <div class="col-sm-4">
          <h2 class="text-center"><%= o.objective_type %></h2>

          <% @valid = o.get_valid_objectives %>
          <% @invalid = o.get_invalid_objectives %>
          <%= pie_chart({ "Objectif rempli" => @valid, "Objectif non rempli" => @invalid, "Absent" => (o.get_total_supports - @valid - @invalid)}) %>
        </div>
    <% end %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="text-center">email</th>
        <th class="text-center">Follow-up 1</th>
        <th class="text-center">Follow-up 2</th>
        <th class="text-center">Delivery</th>
        <% if current_user.role == 1 %>
          <th class="text-center">Supprimer le supporter</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @project.project_fundings.each do |p| %>
        <tr>
          <td class="text-center"><%= p.user.email %></td>
          <td class="text-center"><button class="btn btn-<%= p.user.is_present(@project, 0) ? "success" : "danger" %>"><%= p.user.is_present(@project, 0) ? "Présent" : "Absent" %></button></td>
          <td class="text-center"><button class="btn btn-<%= p.user.is_present(@project, 1) ? "success" : "danger" %>"><%= p.user.is_present(@project, 1) ? "Présent" : "Absent" %></button></td>
          <td class="text-center"><button class="btn btn-<%= p.user.is_present(@project, 2) ? "success" : "danger" %>"><%= p.user.is_present(@project, 2) ? "Présent" : "Absent" %></button></td>
          <% if current_user.role == 1 %>
            <td class="text-center">   <%= link_to "Supprimer ce supporter", projects_remove_user_path({:user_id => p.user.id, :project_id => @project.id}), :class => "btn btn-danger", :method => :post, data: { confirm: "Êtes-vous sûr ? Cette action est irréversible"} %></td>
          <% end %>
        </tr>
     <% end %>
    </tbody>
  </table>
</div>

app/app/views/stats/spices.html.erb
<div class="container">
  <h2 class="text-center">Mes <%= money_name %></h2>
  <ul class="list-group">
    <% current_user.project_fundings.each do |p| %>
        <li class="list-group-item">
          <%= p.project.name %>
          <span class="pull-right">
              <button class="btn btn-xs btn-<%= p.status == 0 ? "warning" : "success" %>"><%= p.get_status_name %></button>
              <button class="btn btn-xs btn-success"><%= p.spices %></button>
            </span>
        </li>
    <% end %>
  </ul>
</div>