app/config/routes.rb
Rails.application.routes.draw do
  #get 'setting/index'

  mount Ckeditor::Engine => '/ckeditor'
  # devise_for :users

  resources :visitor do
    get 'historic', on: :member
  end

  get 'authorize' => 'auth#gettoken'

  match "/projects/finished", to: "projects#finished", via: :get
  resources :projects do
      post 'send_spices', on: :member
      post 'set_status', on: :member
      post 'set_objective_status', on: :member
      post 'assign_spices_to_user', on: :member

      get  'objective_validation', on: :member
      get 'assign_spices', on: :member
      get 'clone', on: :member
      get 'historic', on: :member
  end

  match "/projects/remove_user", to: "projects#remove_user_funding", via: :post
  match "/stats/spices", to: "stats#spices", via: :get
  match "/stats/users", to: "stats#user_data", via: :get
  match "/stats/project", to: "stats#project", via: :get
  match "/stats/admin", to: "stats#admin", via: :get
  match "/stats/change_status", to: "stats#change_status", via: :post
  match "/auth/login", to: "auth#login", via: :get
  match "/auth/logout", to: "auth#logout", via: :delete

  match "/setting", to: "setting#index", via: :get
  match "/setting", to: "setting#create", via: :post

  root "projects#index"
end

app/app/models/project.rb
class Project < ApplicationRecord
  has_many :objectives, inverse_of: :project
  accepts_nested_attributes_for :objectives, reject_if: :all_blank, allow_destroy: true
  belongs_to :user
  has_many :project_fundings

  validates_presence_of :name, :spices, :description

  enum status:
  {
      pending:                0,    # Created but not confirmed by admin
      confirmed_by_admin:     1,    # Confirmed by admin user
      kick_off_start:         2,    # Kick-off started : users can send spices
      kick_off_validated:     3,    # Kick-off validated : waiting for follow-up
      follow_up_1_started:    4,    # Follow-up 1 started : users can vote for objective to be completed
      follow_up_1_validated:  5,
      follow_up_2_started:    6,
      follow_up_2_validated:  7,
      delivery_started:       8,
      delivery_validated:     9
  }

  def is_re_fundable
    @projectSup = Project.where(:name => self.name).where("created_at > :start_date", {start_date: self.created_at})
    if nil === @projectSup
      return true
    else
      return Project.statuses[self.status] > 6# && nil == @projectSup
    end
  end

  def get_funded_spices
    if Project.statuses[self.status] > 3
      # Project already funded, no need to check
      return self.spices
    else
      @spices = 0 
      self.project_fundings.each do |s|
        if s.status == 0
          @spices += s.spices
        end
      end
      @spices
    end
  end

  def get_objective_type
    if self.follow_up_1_started? || self.follow_up_1_validated?
      return 0
    elsif self.follow_up_2_started? || self.follow_up_2_validated?
      return 1
    elsif self.delivery_started? || self.delivery_validated?
      return 2
    end
  end

  def assigned_spices
    @spices = ProjectFunding.where({project_id: self.id, status: 2})
    @ret = 0
    @spices.each do |s|
      @ret += s.spices
    end
    @ret
  end

  def get_status
    if self.pending?
      return "En attente de validation par un pédago"
    elsif self.confirmed_by_admin?
      return "En attente de kick-off"
    elsif self.kick_off_start?
      return "Kick-off en cours"
    elsif self.kick_off_validated?
      return "Kick-off validé"
    elsif self.follow_up_1_started?
      return "Follow-up 1 en cours"
    elsif self.follow_up_1_validated?
      return "Follow-up 1 validé"
    elsif self.follow_up_2_started?
      return "Follow-up 2 en cours"
    elsif self.follow_up_2_validated?
      return "Follow-up 2 validé"
    elsif self.delivery_started?
      return "Delivery en cours"
    elsif self.delivery_validated?
      return "Projet terminé"
    end
  end

  def get_status_action
    if self.pending?
      return "Valider le projet"
    elsif self.confirmed_by_admin?
      return "Démarrer le kick-off"
    elsif self.kick_off_start?
      return "Terminer le kick-off"
    elsif self.kick_off_validated?
      return "Démarrer le follow-up 1"
    elsif self.follow_up_1_started?
      return "Terminer le follow-up 1"
    elsif self.follow_up_1_validated?
      return "Démarrer le follow-up 2"
    elsif self.follow_up_2_started?
      return "Terminer le follow-up 2"
    elsif self.follow_up_2_validated?
      return "Démarrer le delivery"
    elsif self.delivery_started?
      return "Terminer le delivery"
    end
  end
end

app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :clone,  :destroy, :historic, :send_spices, :set_status, :objective_validation, :set_objective_status, :assign_spices, :assign_spices_to_user]
  before_action :sanitize_params, only: [:create, :update]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where.not({status: 9})
  end

  def finished
    @projects = Project.where({status: 9})
    render 'index'
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @number_of_project = Project.where({name: @project.name}).size
    respond_to do |format|
      format.html { render :show }
      format.pdf {
        render :pdf => 'show', :layout => 'application.pdf'
      }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.objectives << Objective.new({objective_type: 0})
    @project.objectives << Objective.new({objective_type: 1})
    @project.objectives << Objective.new({objective_type: 2})
  end

  # GET /projects/1/clone
  def clone
    if @project.user == current_user
      @project2 = @project
      @project = Project.new
      @project.name = @project2.name
      @project.git_hub = @project2.git_hub
      @project.description = @project2.description
      @project.objectives << Objective.new({objective_type: 0})
      @project.objectives << Objective.new({objective_type: 1})
      @project.objectives << Objective.new({objective_type: 2})
      render :new
    else
      render :nothing => true, :status => :not_found
    end
  end

  # GET /projects/1/edit
  def edit
    # Patch, if not to_i test always fail.
    if ((@project.status == 0 || @project.pending?) && current_user == @project.user) || current_user.role == 1
      render 'new'
    else
      render :nothing => true, :status => :not_found
    end
  end

  # GET /projects/:id/historic
  def historic
    @projects = Project.where({name: @project.name}).order('created_at desc')
    render :historic
  end
  
  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @nameEverExist = Project.find_by name: @project.name
    if @nameEverExist == nil || (@nameEverExist.user == current_user && @nameEverExist.is_re_fundable)
      @project.user = current_user
      @project.status = 0
      respond_to do |format|
        if @project.save
          format.html { redirect_to @project, :flash => {success: 'Projet créé avec succès'} }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @project, :flash => {error: 'Impossible de crée le projet, ce nom est déjà utilisé'} }
        format.json { render :show, status: :created, location: @project }
      end
    end
  end

  # POSTS 
  def send_spices
    @spices = params[:project][:spices].to_i

    # Check user is not funding itself
    if @project.user != current_user && @project.kick_off_start?
      # Check spices number is correct
      if (advisor_activate && (@spices == investisor_spice || @spices == advisor_spice)) || @spices == investisor_spice
        # Check the project is fundable and user has enough spices

        @end_spices = @project.get_funded_spices + @spices
        if current_user.spices >= @spices && @end_spices <= @project.spices

          # Check user has not funded this project already
          @fundings = ProjectFunding.where(user: current_user)
          @fundings.each do |f|
            if f.project == @project
              redirect_to @project, :flash => { error: "Vous avez déja donné des " + money_name + " à ce projet" }
              return
            end
          end

          # Create funding
          @funding = ProjectFunding.new(user: current_user, project: @project, spices: @spices, comment: params[:project][:name])
          if @funding.save

            # Check if project is fully funded
            if @end_spices == @project.spices
              @project.kick_off_validated!
              @project.save
            end
            redirect_to root_path, :flash => { success: "Vous avez donné des " + money_name + " à ce projet" }
          end
        end
      end
    elsif current_user.role == 1
      @user = User.find_by_email(params[:project][:description])
      if @user.nil?
        @user = User.new(email: params[:project][:description])
        @user.save
      end
      @funding = ProjectFunding.new(user: @user, project: @project, spices: @spices, comment: params[:project][:name])
      if @funding.save
        redirect_to project_path(@project), :flash => { success: "Vous avez donné des " + money_name + " à ce projet" }
      end
    end
  end

  def set_status
    if current_user.role == 1
      @status = params[:status].to_i

      @project.status = @status
      if @status == 3
        if @project.get_funded_spices != @project.spices
          #  When we end the kick-off and there is not enough spices given
          # The project is reset to its former state
          @project.status = 1
          @project.project_fundings.each do |p|
            p.destroy
          end
        end
      elsif @status == 5 || @status == 7 || @status == 9
        # Check 80% of stats validated the objective
        @objective = Objective.where({project_id: @project.id, objective_type: @project.get_objective_type}).take
        @stats = @objective.get_valid_objectives.to_f / @objective.get_total_supports.to_f

        # Objective is passed if more than 80% of supported validated the completion
        if @stats >= 0.8
          @objective.passed = true
          @objective.save

          # if the delivery is validated we send spices to the supporters and advisors
          if @status == 9
            @project.project_fundings.each do |p|
              p.status = 1
              p.save
            end
          end
        else
          @project.status = @status - 2
          @objective.objective_validations.destroy_all
        end
      end

      if @project.save
        redirect_to root_path
      else
        redirect_to @project, :flash => { error: 'Erreur lors de la mise à jour du projet' }
      end
    else
      render :nothing =>  true, :status => :forbidden
    end
  end

  def set_objective_status
    # Check if the user has voted already or not
    @test = ObjectiveValidation.where({user_id: current_user.id, objective_id: params[:objective_id]}).take
    if @test.nil?
      @objective = Objective.find(params[:objective_id])
      @objective_validation = ObjectiveValidation.new
      @objective_validation.objective = @objective
      @objective_validation.user = current_user
      @objective_validation.passed = params[:passed]
      @objective_validation.save

      redirect_to objective_validation_project_path(@project)
    else
      redirect_to objective_validation_project_path(@project), :flash => { error: 'Vous avez déjà donné votre avis sur cet objectif' }
    end
  end

  def objective_validation
    if @project.follow_up_1_started?
      @objective = Objective.where({project_id: @project.id, objective_type: 0}).take
    elsif @project.follow_up_2_started?
      @objective = Objective.where({project_id: @project.id, objective_type: 1}).take
    elsif @project.delivery_started?
      @objective = Objective.where({project_id: @project.id, objective_type: 2}).take
    end
    @stats = @objective.get_valid_objectives.to_f / @objective.get_total_supports
    if @stats.nan?
      @stats = 0
    else
      @stats *= 100
      @stats = @stats.to_i
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if (current_user == @project.user && (@project.status == 0 || @project.pending?)) || current_user.role == 1
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to @project, :flash => { success: 'Projet correctement mis à jour' } }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if current_user == @project.user || current_user.role == 1
      @project.objectives.each do |obj|
        obj.objective_validations.destroy_all
        obj.destroy
      end
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_url, :flash => { success: 'Projet supprimé avec succès' } }
        format.json { head :no_content }
      end
    end
  end

  def assign_spices
  end

  def assign_spices_to_user
    if current_user.role == 1 && @project.delivery_validated?
      @user = User.find_by_email(params[:project][:user])
      @max_spices = @project.spices - @project.assigned_spices

      if params[:project][:spices].to_i <= @max_spices && !@user.nil?
        @funding = ProjectFunding.new
        @funding.spices = params[:project][:spices]
        @funding.user = @user
        @funding.project = @project
        @funding.status = 2
        if @funding.save
          redirect_to root_path, :flash => {success: money_name + ' correctement assignés'}
        else
          redirect_to assign_spices_project_path(@project), :flash => {error: "Une erreur s'est produite" }
        end
      else
        redirect_to assign_spices_project_path(@project), :flash => {error: "Une erreur s'est produite, vérifiez que le nombre d'" + money_name + " et est correct et que l'utilisateur existe"}
      end
    else
      render :nothing => true, :status => :forbidden
    end
  end

  def remove_user_funding
    if current_user.role == 1
      @user = User.find_by_id(params[:user_id])

app/app/helpers/projects_helper.rb
module ProjectsHelper
end

app/app/views/projects/_form.html.erb
<div class="container">
  <%= form_for(@project, :html => { :class=> "form-horizontal" }) do |f| %>

    <div class="form-group">
      <%= f.text_field :name, :class => "form-control", :placeholder => "Nom du projet" %>
    </div>

    <div class="form-group">
        <%= f.number_field :spices, :class => "form-control", :placeholder => money_name.capitalize + " demandé" %>
    </div>

    <div class="form-group">
        <%= f.text_field :git_hub, :class => "form-control", :placeholder => "Dépot GitHub" %>
    </div>


    <div class="form-group">
        <h2 class="text-center">Description et porteur(s) du projet:</h2>
        <%= f.cktext_area :description, class: 'someclass', ckeditor: { language: 'fr'} %>
    </div>

    <% @project.objectives.each_with_index do |objective, index| %>
      <%= f.fields_for :objectives, objective do |fq| %>
        <%= render 'objective_fields', :f => fq, :objective => objective, :index => index %>
      <% end %>
    <% end %>

    <div class="form-group">
      <div class="span7 text-center">
        <button type="submit" class="btn btn-default">Valider</button>
      </div>
    </div>
  <% end %>

</div>

<script>
  // Editor to lisent
  let editorInstance = CKEDITOR.instances["project_description"];
  // Variables associates
  let picturesPush = {}; // Email of picture ever push in editor
  let nbElementInEditor = editorInstance.getData().length; // Last size on editor before 'change' event

  /*
  ** Put photo get on epitech intranet in ckeditor.
  */
  function putPicture(editor, name){
    const image_tag='<img src="https://cdn.local.epitech.eu/userprofil/commentview/' + name + '.jpg" alt="' + name + '">';

    editor.insertHtml(image_tag);
  }

  /*
  ** Check if there are epitech email in editor and load map, can insert image in editor
  ** editor -> CKEDITOR to analyse
  ** insertImage -> if equal true insert image in editor
  */
  function emailInCkeditor(editor, insertImage){
    const str = editor.getData();

    if (nbElementInEditor <= str.length){ // Search all email
      const regex = /[a-z]+\.[a-z]+@epitech.eu\b/g;
      const match = str.match(regex);

      if (null !== match){
        for (let i = 0; i < match.length; ++i){
          if (undefined === picturesPush[match[i]]){
            picturesPush[match[i]] = 1;
            if (true === insertImage){
              putPicture(editor, match[i].replace("@epitech.eu", ""));
            }
          }
        }
      }
    }else{
      // Re load map.
      nbElementInEditor = str.length;
      picturesPush = {};
      emailInCkeditor(editor, false);
    }
    nbElementInEditor = str.length;
  }

  editorInstance.on('change', function() { // add event
      emailInCkeditor(editorInstance, true);
  });

  emailInCkeditor(editorInstance, false); // Load map
</script>

app/app/views/projects/_objective_fields.html.erb
<div class="nested-fields">
  <h2 class="text-center"><%= objective.objective_type %></h2>

  <div class="form-group field">
    <%= f.date_field :date, :class => "form-control datepicker", :required => true, :placeholder => "Date de rendu" %>
  </div>

  <div class="form-group field">
    <%= f.cktext_area :description, :class => "form-control", :required => true %>
  </div>

  <div class="hidden">
    <%= f.number_field :objective_type, :value => index %>
  </div>
</div>

<script type="text/javascript">
  $('.datepicker').datepicker({
    format: 'yyyy-mm-dd'
  });
</script>

app/app/views/projects/assign_spices.html.erb
<div class="container">
  <%= form_for(@project, :url => { action: "assign_spices_to_user" }, :method => "post", :html => {:class => "form-horizontal" }) do |f| %>
      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Nombre d'épices</label>
        <div class="col-sm-10">
          <%= f.number_field :spices, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Utilisateur</label>
        <div class="col-sm-10">
          <%= f.email_field :user, :class => "form-control", :value => "", :placeholder => @project.user.email %>
        </div>
      </div>

      <div class="text-center">
        <button type="submit" class="btn btn-default">Attribuer des épices à l'utilisateur</button>
      </div>
  <% end %>
</div>

app/app/views/projects/edit.html.erb
<%= render 'form', project: @project %>

app/app/views/projects/historic.html.erb
<h1 class="text-center"><%= @projects.first.name %></h1>

<% @projects.each_with_index do |p, index| %>
    <p class="text-center">
        <%= link_to project_path(p) do %>
            <% if p.objectives.size > 0 %>
                Version <%= @projects.size - index %>: Du <%= p.created_at.to_formatted_s(:db) %> au <%= p.objectives.last.date.to_formatted_s(:db) %>
            <% else %>
                Version <%= @projects.size - index %> en cours de validation.
            <% end %>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <%= Project.statuses[p.status].to_f * 100 / 9 %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                    <span style="color: <%= (Project.statuses[p.status] < 5 ? "black" : "#F1F1F1") %>;"><%= p.get_status %></span>
                </div>
            </div>
        <% end %>
    </p>
<% end %>

app/app/views/projects/index.html.erb
<div class="container">
  <% if @projects.empty? %>
    <div class="text-center" style="font-size: 20px">
      Aucun projet
    </div>
  <% else %>
    <% @projects.each do |p| %>
    <% if current_user.role == 1 || !p.pending? || current_user == p.user %>
      <div class="list-group">
        <div class="list-group-item clearfix">
          <%= link_to project_path(p) do %>
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <%= Project.statuses[p.status].to_f * 100 / 9 %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                  <span style="color: <%= (Project.statuses[p.status] < 5 ? "black" : "#F1F1F1") %>;"><%= p.get_status %></span>
                </div>
              </div>
              <%= p.name %>
            <% end %>
            <span class="pull-right">
              <div class="btn-group" role="group" aria-label="...">

                <button class="btn btn-default" disabled><%= p.get_funded_spices %>/<%= p.spices %></button>
                <% if p.follow_up_1_started? || p.follow_up_2_started? || p.delivery_started? %>
                  <%= link_to objective_validation_project_path(:id => p.id), :class => "btn btn-default", data: {toggle: "tooltip", placement: "top"}, :title => "Voir la validation" do %>
                    <span class="glyphicon glyphicon-ok"></span>
                  <% end %>
                <% end %>

                <%= link_to project_path(p, format: :pdf), :class => "btn btn-default", target: '_blank', data: {toggle: "tooltip", placement: "top"}, :title => "Voir le PDF" do %>
                  <span class="glyphicon glyphicon-download"></span>
                <% end %>

                <%= link_to stats_project_path(:id => p.id), :class => "btn btn-default", data: {toggle: "tooltip", placement: "top"}, :title => "Voir les statistiques" do %>
                  <span class="glyphicon glyphicon-list-alt"></span>
                <% end %>

                <% if current_user.role == 1 %>
                  <%= link_to set_status_project_path(:id => p.id, :status => Project.statuses[p.status] + 1), :method => 'post', :class => "btn btn-default", data: {toggle: "tooltip", placement: "top", :confirm => 'Vous êtes sur ?'}, :title => p.get_status_action do %>
                    <% if p.follow_up_1_started? || p.follow_up_2_started? || p.delivery_started? %>
                      <span class="glyphicon glyphicon-stop"></span>
                    <% elsif p.pending? %>
                      <span class="glyphicon glyphicon-ok"></span>
                    <% else %>
                      <span class="glyphicon glyphicon-play"></span>
                    <% end %>
                  <% end %>

                  <div class="btn-group" role="group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="glyphicon glyphicon-option-vertical"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Modifier le projet', edit_project_path(p) %></li>
                      <li><%= link_to 'Supprimer le projet', p, method: :delete, data: { confirm: 'Etes vous sur ?' } %></li>
                      <% if p.delivery_validated? && p.assigned_spices < p.spices %>
                        <li><%= link_to "Assigner des épices aux porteurs de projet", assign_spices_project_path(p) %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              </div>
            </span>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/app/views/projects/new.html.erb
<%= render 'form', project: @project %>

app/app/views/projects/objective_validation.html.erb
<div class="container">
  <h1 class="text-center"><%= @objective.objective_type %> pour <%= @project.name %></h1>

  <%= @objective.description.html_safe %>

  <hr>

  <h2 class="text-center">
    <%= @stats %>&#37; des supporters ont validé cet objectif
  </h2>
  <h2 class="text-center"><%= @objective.get_user_votes %> / <%= @objective.get_total_supports %> supporters ont voté</h2>

  <% if @objective.user_has_voted_objective(current_user.id).nil? && current_user.is_funding_project(@project.id) %>
    <h2 class="text-center">Les objectifs sont-ils atteints ?

      <%= link_to set_objective_status_project_path(:objective_id => @objective.id, :passed => true), :class=> "btn btn-success", :method => 'post' do %>
          <span class="glyphicon glyphicon-ok"></span>
      <% end %>

      <%= link_to set_objective_status_project_path(:objective_id => @objective.id, :passed => false), :class=> "btn btn-danger", :method => 'post' do %>
          <span class="glyphicon glyphicon-remove"></span>
      <% end %>
    </h2>
  <% end %>

</div>

app/app/views/projects/show.html.erb
<div class="container">
  
  <h1 class="text-center"><%= @project.name %></h1>
  <% if false == @project.git_hub.to_s.empty? %>
    <p><strong>GitHub:</strong> <%= @project.git_hub %></p>
  <% end %>

  <h2>Présentation</h2>
  <%= @project.description.html_safe %>

  <% @project.objectives.each_with_index do |objective, index| %>
      <h2><%= objective.objective_type %> <%= objective.date %></h2>
    <%= objective.description.html_safe %>
  <% end %>

  <% if current_user == @project.user && (@project.follow_up_2_validated? || @project.delivery_started? || @project.delivery_validated?) %>
    <%= link_to clone_project_path(:id => @project.id) do %>Poursuivre le projet<% end %>
  <% end %>
    
  <% if @number_of_project > 1 %>
    <%= link_to historic_project_path(:id => @project.id) do %>Historique du projet<% end %>
  <% end %>

  <% if current_user != @project.user && @project.kick_off_start? %>
    <h2>Soutenir ce projet</h2>
    <%= form_for(@project, :url => { action: "send_spices" }, :method => "post", :html => { :class => "form-horizontal" }) do |f| %>
      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Nombre
          <% if 'aeioué'.include? money_name[0]  %>
            d'
          <% else %>
              de
          <% end %>
          <%= money_name %></label>
        <div class="col-sm-10">
          <% if advisor_activate %>
            <%= f.select :spices, [investisor_spice, advisor_spice], {} %>
          <% else %>
              <%= f.select :spices, [investisor_spice], {} %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Commentaire</label>
        <div class="col-sm-8">
          <%= f.text_field :name, :class => "form-control", :value => "", :required => true %>
        </div>
        <div class="col-sm-2">
          <button class="btn btn-default" type="submit">Soutenir ce projet</button>
        </div>
      </div>
    <% end %>
  <% end %>

  <!--<% if current_user.role == 1 %>-->
    <!--<%= form_for(@project, :url => {action: "send_spices"}, :method => "post", :html => { :class => "form-horizontal" }) do |f| %>-->
      <!--<div class="form-group">-->
        <!--<label for="inputEmail3" class="col-sm-2 control-label">Nombre d'" + <%= money_name %> + " (max 5)</label>-->
        <!--<div class="col-sm-10">-->
          <!--<%= f.select :spices, [5, 15], {} %>-->
        <!--</div>-->
      <!--</div>-->
      <!--<div class="form-group">-->
        <!--<label class="col-sm-2 control-label">Commentaire</label>-->
        <!--<div class="col-sm-10">-->
          <!--<%= f.text_field :name, :class => "form-control", :value => "", :required => true %>-->
        <!--</div>-->

      <!--</div>-->
      <!--<div class="form-group">-->
        <!--<label class="col-sm-2 control-label">Email</label>-->
        <!--<div class="col-sm-8">-->
          <!--<%= f.text_field :description, :class => "form-control", :value => "", :required => true %>-->
        <!--</div>-->
        <!--<div class="col-sm-2">-->
          <!--<button class="btn btn-default" type="submit">Ajouter un supporter</button>-->
        <!--</div>-->
      <!--</div>-->
    <!--<% end %>-->
  <!--<% end %>-->

  <ul class="list-group">
    <% @project.project_fundings.each do |p| %>
      <li class="list-group-item">
        <%= p.user.email %>&nbsp;|&nbsp;<%= p.comment %>
        <span class="pull-right">
          <button class="btn btn-xs btn-success"><%= p.spices %></button>
        </span>
      </li>
    <% end %>
  </ul>
</div>

app/app/views/projects/show.pdf.erb
<div class="container">
  <h1 class="text-center"><%= @project.name %></h1>

  <% if false == @project.git_hub.to_s.empty? %>  
    <h3>GitHub : <%= @project.git_hub %></h3>
  <% end %>
  
  <%= @project.description.html_safe %>

  <% @project.objectives.each do |obj| %>
    <h2><%= obj.objective_type %> <%= obj.date %></h2>
    <%= obj.description.html_safe %>
  <% end %>
</div>